# Uncomment the next line to define a global platform for your project
# platform :ios, '13.4'

target 'news_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  target 'news_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'news_appUITests' do
    # Pods for testing
  end

end
